<Container>
    rows: 3
    padding: 50

    krakozjabra: text_input
    label_widget: label

    TextInput:
        id: text_input
        size_hint: 1, 0.5
        multiline: False
        font_size: 40

    Label:
        id: label
        text: 'Some text'
        font_size: 40


    FloatLayout:
        Button:
            size_hint: 0.5, 0.4
            pos_hint: {'center_x': 0.5, 'y':0.1}
            text: 'desicion_3'

            on_release:
                root.change_text()

